### PR TITLE
Fixed issue #11

### PR DESCRIPTION
**Pull request by devoh747**
Fixed import statement for adafruit_fancyled.

### CODE REVIEW

**Review by ladyada — APPROVED** [review]

**Comment by ladyada** [comment]
@devoh747 what'd ya test this on?
@caternuson wanna try it on the ft232h? :)

**Comment by devoh747** [comment]
I tested on a CPX running CP 4.1.0 and using libs 4.x from 10/4

I also have a CPXBFLE if you want me to test it there as well using CP 5.
Actually I have a GrandCentral m4, ItsyBitsy M4, CPX, CPXBFLE, Feather M4 and a Feather ESP32 Huzzah..  I'm turning into a collector  :)

**Comment by caternuson** [comment]
@ladyada FWIW - tested and works with FT232H

@devoh747 - thanks for the fix and working through all the hiccups to get past Travis

**Comment by ladyada** [comment]
zoom rad @caternuson can add that to your guidepage :)

**Pull request merged**
